type Provider = {
  id: string;
  name: string;
  description: string;
  rating: number | null;
  reviews: number | null;
  verified: boolean;
  services: string[];
  priceRange: string;
  location: string;
};

export const PROVIDERS: Provider[] = [
  {
    id: 'london-insulating-homes-ltd',
    name: 'Insulating Homes Ltd',
    description: 'Specialists in high-efficiency insulation and cavity wall treatments. Full-service environmental health solutions for residential properties.',
    rating: 4.6,
    reviews: 53,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-insulation4less-ltd',
    name: 'Insulation4less Ltd',
    description: 'Leading supplier of insulation materials and building supplies. Comprehensive e-commerce service with same-day delivery options available.',
    rating: 4.6,
    reviews: 353,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-safe-eco-fixes-ltd',
    name: 'Safe Eco-Fixes Ltd',
    description: 'Specialists in eco-friendly insulation solutions. Certified expertise in energy-efficient building treatments.',
    rating: 4.7,
    reviews: 51,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-thermal-guardian-ltd',
    name: 'Thermal Guardian Ltd',
    description: 'Specialists in high-efficiency insulation and solar integration. Full roof and thermal solutions with online quotes.',
    rating: 4.8,
    reviews: 47,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-mtc-insulation',
    name: 'MTC Insulation',
    description: 'Specialists in premium insulation installation and thermal efficiency improvements.',
    rating: 5.0,
    reviews: 6,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-eco-save-energy',
    name: 'Eco Save Energy',
    description: 'Specialists in sustainable insulation solutions and energy efficiency.',
    rating: 5.0,
    reviews: 1,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-thermofoam-london',
    name: 'ThermoFoam London',
    description: 'Specialists in spray foam insulation and thermal efficiency. Comprehensive isolation materials supplier.',
    rating: null,
    reviews: null,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-heat-pump-source',
    name: 'Heat Pump Source',
    description: 'Specialists in high-efficiency heat pump installation and heating solutions.',
    rating: 5.0,
    reviews: 7,
    verified: true,
    services: ['Heat Pumps', 'Heating'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-heating-for-london',
    name: 'Heating for London',
    description: 'Professional heating engineers specializing in boiler installation and maintenance. Gas-certified installation services.',
    rating: 5.0,
    reviews: 93,
    verified: true,
    services: ['Heat Pumps', 'Heating'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-city-boiler-repair',
    name: 'City Boiler Repair',
    description: 'Specialists in boiler repair and gas heating solutions. Emergency call-out services available.',
    rating: 4.7,
    reviews: 80,
    verified: true,
    services: ['Heat Pumps', 'Heating'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-underfloor-heating-london',
    name: 'Underfloor Heating London',
    description: 'Specialists in underfloor heating systems and thermal distribution.',
    rating: 5.0,
    reviews: 3,
    verified: true,
    services: ['Heat Pumps', 'Heating'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-plusheat',
    name: 'PlusHeat',
    description: 'Specialists in heating systems, boiler installation, and plumbing services. Comprehensive home climate solutions.',
    rating: 4.5,
    reviews: 2146,
    verified: true,
    services: ['Heat Pumps', 'Heating'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-climate-innovations-ltd',
    name: 'Climate Innovations LTD',
    description: 'Specialists in HVAC systems and heating solutions.',
    rating: 3.7,
    reviews: 6,
    verified: true,
    services: ['Heat Pumps', 'Heating'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-solar-batteries-uk',
    name: 'Solar Batteries UK',
    description: 'Specialists in solar battery storage and renewable energy systems.',
    rating: 5.0,
    reviews: 33,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-solar-panel-installers-london',
    name: 'Solar Panel Installers London',
    description: 'Specialists in solar panel installation and renewable energy systems. Maintenance and monitoring services included.',
    rating: 5.0,
    reviews: 4,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-renewable-energy-experts',
    name: 'Renewable Energy Experts',
    description: 'Specialists in solar energy installation and EV charging infrastructure. Renewable energy consultancy services.',
    rating: 5.0,
    reviews: 23,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-excel-energy',
    name: 'Excel Energy',
    description: 'Specialists in solar panel installation and energy storage solutions. Green energy transition specialists.',
    rating: 5.0,
    reviews: 17,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-ecobright-energy-group',
    name: 'Ecobright Energy Group',
    description: 'Specialists in solar equipment supply and renewable energy systems.',
    rating: 5.0,
    reviews: 7,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-capture-energy',
    name: 'Capture Energy',
    description: 'Specialists in solar equipment and battery storage solutions.',
    rating: 5.0,
    reviews: 3,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-powervault',
    name: 'Powervault',
    description: 'Specialists in battery storage and energy systems manufacturing.',
    rating: 3.6,
    reviews: 28,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-ecotarget',
    name: 'EcoTarget',
    description: 'Specialists in green energy solutions, solar installation, and energy equipment supply.',
    rating: 4.1,
    reviews: 111,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-sash-windows-london',
    name: 'Sash Windows London',
    description: 'Specialists in sash windows and double glazing installation. UPVC and traditional window solutions.',
    rating: 4.8,
    reviews: 180,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-london-window-and-door-repairs',
    name: 'London Window and Door Repairs',
    description: 'Specialists in window repair and double glazing installation. Accessible premises with on-site services.',
    rating: 5.0,
    reviews: 23,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-mortice-green-sash-window-repairs-london',
    name: 'Mortice & Green Sash Window Repairs London',
    description: 'Specialists in sash window repairs and glass solutions. Traditional and modern window expertise.',
    rating: 4.3,
    reviews: 22,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-central-london-emergency-glass-replacement',
    name: 'Central London Emergency Glass Replacement',
    description: 'Specialists in emergency glass replacement and double glazing services. Available 24/7.',
    rating: 5.0,
    reviews: 48,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-century-sash-windows',
    name: 'Century Sash Windows',
    description: 'Specialists in sash windows and professional glazing installation. On-site installation services.',
    rating: 5.0,
    reviews: 52,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-restore-my-window-ltd',
    name: 'Restore my window LTD',
    description: 'Specialists in window restoration and double glazing. Comprehensive building restoration services.',
    rating: 4.9,
    reviews: 33,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-all-seal-glazing-ltd',
    name: 'All Seal Glazing Ltd',
    description: 'Specialists in glass repair and glazing solutions. Industrial-grade glass expertise.',
    rating: 5.0,
    reviews: 124,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-zippey-upvc-door-window-repairs',
    name: 'Zippey uPVC Door & Window Repairs',
    description: 'Specialists in UPVC window and door repairs. Emergency repair services available.',
    rating: 5.0,
    reviews: 42,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-jr-ventilation',
    name: 'JR Ventilation',
    description: 'Specialists in HVAC systems and ventilation equipment manufacturing.',
    rating: 4.6,
    reviews: 21,
    verified: true,
    services: ['Windows'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-garage-door-repair-london',
    name: 'Garage Door Repair London',
    description: 'Specialists in garage door supply and repair services.',
    rating: 5.0,
    reviews: 12,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-victorian-front-door',
    name: 'Victorian Front Door',
    description: 'Specialists in high-end door supply and installation. Accessible premises with on-site services.',
    rating: 5.0,
    reviews: 5,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-skilled-shutter-repair-london',
    name: 'Skilled Shutter Repair London',
    description: 'Specialists in shopfront doors and aluminum solutions. Emergency 24/7 services available.',
    rating: 5.0,
    reviews: 23,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-secure-house-ltd',
    name: 'Secure House Ltd',
    description: 'Specialists in security doors and window systems. PVC door and security solutions.',
    rating: 5.0,
    reviews: 61,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-top-security-doors',
    name: 'Top Security Doors',
    description: 'Specialists in security doors and manufacturing. Garage door systems available.',
    rating: 5.0,
    reviews: 14,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-doors-of-steel',
    name: 'Doors of Steel',
    description: 'Specialists in steel doors and window solutions. Complete renovation services.',
    rating: 5.0,
    reviews: 20,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-smart-ventilation-solutions-ltd',
    name: 'Smart Ventilation Solutions Ltd',
    description: 'Specialists in mechanical ventilation systems and solutions.',
    rating: 5.0,
    reviews: 5,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-air-options-ltd',
    name: 'Air Options Ltd',
    description: 'Specialists in air conditioning and HVAC systems installation.',
    rating: 5.0,
    reviews: 62,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-aircon-company-london',
    name: 'Aircon Company London',
    description: 'Specialists in air conditioning systems and climate control.',
    rating: 5.0,
    reviews: 7,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-london-ac-ltd',
    name: 'London AC Ltd',
    description: 'Specialists in air conditioning installation and systems.',
    rating: 5.0,
    reviews: 2,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-the-london-air-conditioning-installation',
    name: 'The London Air Conditioning Installation',
    description: 'Specialists in professional air conditioning installation services.',
    rating: 5.0,
    reviews: 24,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-lux-cooling-group',
    name: 'Lux Cooling Group',
    description: 'Specialists in air conditioning systems and cooling solutions.',
    rating: 5.0,
    reviews: 28,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-mtp-cooling-ltd',
    name: 'MTP Cooling Ltd',
    description: 'Specialists in air conditioning installation and repair services.',
    rating: 5.0,
    reviews: 3,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-damp-proofing-london-sw',
    name: 'Damp Proofing London SW',
    description: 'Professional damp proofing and waterproofing services.',
    rating: null,
    reviews: null,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-damp-proofing-direct-ltd',
    name: 'Damp Proofing Direct Ltd',
    description: 'Professional construction and damp-proofing solutions.',
    rating: null,
    reviews: null,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-south-east-damp-specialist',
    name: 'South East Damp Specialist',
    description: 'Specialists in waterproofing and building restoration. Comprehensive interior and flooring solutions.',
    rating: 5.0,
    reviews: 3,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-damp-survey-london',
    name: 'Damp Survey London',
    description: 'Specialists in damp surveying and professional waterproofing. Building surveyor certified.',
    rating: 4.8,
    reviews: 29,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-city-dampcoursing-ltd',
    name: 'City Dampcoursing Ltd',
    description: 'Specialists in damp-course installation and building restoration.',
    rating: 5.0,
    reviews: 12,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-master-waterproofing-and-renovations-limited',
    name: 'Master Waterproofing and Renovations Limited',
    description: 'Specialists in waterproofing and building renovations. Professional restoration services.',
    rating: 5.0,
    reviews: 20,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'london-crown-preservation-damp-proofing',
    name: 'Crown Preservation Damp Proofing',
    description: 'Specialists in damp proofing and building preservation. Restoration and construction expertise.',
    rating: 4.7,
    reviews: 78,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'London',
  },
  {
    id: 'manchester-conservatory-roof-insulation-manchester',
    name: 'Conservatory Roof Insulation Manchester',
    description: 'Specialists in conservatory insulation and thermal efficiency solutions.',
    rating: 4.0,
    reviews: 4,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-salford-loft-insulation-company',
    name: 'Salford Loft Insulation Company',
    description: 'Specialists in loft insulation and thermal efficiency improvements.',
    rating: 5.0,
    reviews: 3,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-efficient-loft-insulation',
    name: 'Efficient Loft Insulation',
    description: 'Specialists in professional loft insulation and energy efficiency.',
    rating: 4.8,
    reviews: 33,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-minster-manchester',
    name: 'Minster Manchester',
    description: 'Comprehensive insulation materials supplier and building materials specialist.',
    rating: 4.5,
    reviews: 15,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-great-british-insulation',
    name: 'Great British Insulation',
    description: 'Specialists in high-efficiency insulation solutions.',
    rating: null,
    reviews: null,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-warmaroof-uk-ltd',
    name: 'Warmaroof Uk Ltd',
    description: 'Specialists in roof insulation and thermal efficiency systems.',
    rating: null,
    reviews: null,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-advanced-cavity-wall-insulation-services',
    name: 'Advanced Cavity Wall Insulation Services',
    description: 'Specialists in cavity wall insulation and thermal improvements.',
    rating: 5.0,
    reviews: 1,
    verified: true,
    services: ['Insulation'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-flame-on-boiler-installation-manchester',
    name: 'Flame On Boiler Installation Manchester',
    description: 'Specialists in boiler installation and heating systems. LGBTQ+ friendly business. Gas-certified engineers.',
    rating: 4.8,
    reviews: 76,
    verified: true,
    services: ['Heating', 'Heat Pumps'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-pipeworks-manchester',
    name: 'Pipeworks Manchester',
    description: 'Specialists in heating, plumbing, and gas installation services. Online quotes available.',
    rating: 4.5,
    reviews: 153,
    verified: true,
    services: ['Heating', 'Heat Pumps'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-olympus-plumbing-heating',
    name: 'Olympus Plumbing & Heating',
    description: 'Specialists in gas heating and boiler installation. Radiator repair and maintenance services. LGBTQ+ friendly.',
    rating: 4.9,
    reviews: 82,
    verified: true,
    services: ['Heating', 'Heat Pumps'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-heatingcare-co-uk',
    name: 'Heatingcare.co.uk',
    description: 'Heating and plumbing specialists.',
    rating: 3.7,
    reviews: 3,
    verified: true,
    services: ['Heating', 'Heat Pumps'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-ontime-eco-energy-solutions-ltd',
    name: 'Ontime Eco Energy Solutions Ltd',
    description: 'Specialists in eco-friendly heating solutions.',
    rating: 5.0,
    reviews: 2,
    verified: true,
    services: ['Heating', 'Heat Pumps'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-atmostherm-ltd',
    name: 'Atmostherm Ltd',
    description: 'Specialists in HVAC systems and heating solutions. Equipment and installation services.',
    rating: 5.0,
    reviews: 7,
    verified: true,
    services: ['Heating', 'Heat Pumps'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-k2-heating-and-cooling-solutions-ltd',
    name: 'K2 Heating and Cooling Solutions Ltd',
    description: 'Specialists in HVAC systems, heating, and cooling solutions.',
    rating: 3.5,
    reviews: 8,
    verified: true,
    services: ['Heating', 'Heat Pumps'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-kast-energy-solar-panels-manchester',
    name: 'Kast Energy Solar Panels Manchester',
    description: 'Specialists in solar panel installation and renewable energy systems.',
    rating: 5.0,
    reviews: 4,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-voltedge-greentech',
    name: 'Voltedge Greentech',
    description: 'Specialists in solar panel installation and renewable energy solutions for Greater Manchester.',
    rating: 5.0,
    reviews: 1,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-solar-maintenance-solutions',
    name: 'Solar Maintenance Solutions',
    description: 'Specialists in solar maintenance and renewable energy systems. Professional installation and aftercare. Accessible facilities.',
    rating: 4.9,
    reviews: 232,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-atlantic-renewables',
    name: 'Atlantic Renewables',
    description: 'Specialists in solar installation and renewable energy systems. Female-owned business. Accessible premises.',
    rating: 5.0,
    reviews: 36,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-eco-energy-rating-ltd',
    name: 'Eco Energy Rating Ltd',
    description: 'Specialists in solar energy and battery storage solutions. LGBTQ+ friendly business.',
    rating: 5.0,
    reviews: 5,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-storelectric-limited',
    name: 'Storelectric Limited',
    description: 'Specialists in energy storage and equipment solutions.',
    rating: null,
    reviews: null,
    verified: true,
    services: ['Solar', 'Battery Storage'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-trafford-windows',
    name: 'Trafford Windows',
    description: 'Specialists in windows, doors, and glazing solutions.',
    rating: 4.1,
    reviews: 80,
    verified: true,
    services: ['Windows', 'Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-finestra-uk-upvc-windows-doors-manchester',
    name: 'FINESTRA UK - UPVC Windows & Doors Manchester',
    description: 'Specialists in UPVC window and door installation.',
    rating: 3.5,
    reviews: 15,
    verified: true,
    services: ['Windows', 'Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-malbern-trade-windows-ltd',
    name: 'Malbern Trade Windows Ltd',
    description: 'Specialists in window supply and installation. Industrial-scale solutions.',
    rating: 4.9,
    reviews: 40,
    verified: true,
    services: ['Windows', 'Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-window-surgeon',
    name: 'Window Surgeon',
    description: 'Specialists in double glazing and glass repair services.',
    rating: 5.0,
    reviews: 10,
    verified: true,
    services: ['Windows', 'Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-long-life-windows-ltd',
    name: 'Long Life Windows Ltd.',
    description: 'Specialists in glass and window solutions.',
    rating: 4.7,
    reviews: 10,
    verified: true,
    services: ['Windows', 'Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-crystal-windows-mcr',
    name: 'Crystal Windows MCR',
    description: 'Professional glazing specialists.',
    rating: 5.0,
    reviews: 3,
    verified: true,
    services: ['Windows', 'Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-bee-manchester-ltd',
    name: 'Bee Manchester Ltd',
    description: 'Specialists in windows, doors, and glazing solutions.',
    rating: 4.7,
    reviews: 14,
    verified: true,
    services: ['Windows', 'Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-manchester-joinery-interiors-ltd',
    name: 'Manchester Joinery & Interiors Ltd',
    description: 'Specialists in door supply and interior joinery solutions.',
    rating: 5.0,
    reviews: 8,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-westwood-security-shutters-ltd',
    name: 'Westwood Security Shutters Ltd',
    description: 'Specialists in security shutters and door systems. Industrial engineering services.',
    rating: 4.5,
    reviews: 59,
    verified: true,
    services: ['Doors'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-premier-air-control-ltd',
    name: 'Premier Air Control Ltd',
    description: 'Specialists in air conditioning and HVAC systems.',
    rating: 5.0,
    reviews: 4,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-ultimate-cooling-ltd',
    name: 'Ultimate Cooling Ltd',
    description: 'Specialists in air conditioning and refrigeration services.',
    rating: 5.0,
    reviews: 5,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-temperature-control-ltd',
    name: 'Temperature Control Ltd',
    description: 'Air conditioning systems specialist.',
    rating: 3.0,
    reviews: 4,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-clean-green-energy-ltd',
    name: 'Clean Green Energy Ltd',
    description: 'Specialists in air conditioning and renewable energy solutions.',
    rating: 4.3,
    reviews: 6,
    verified: true,
    services: ['Ventilation', 'HVAC'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-damp-proofing-manchester',
    name: 'Damp Proofing Manchester',
    description: 'Professional damp proofing and water damage restoration services.',
    rating: null,
    reviews: null,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-damp-solutions-uk-manchester',
    name: 'Damp Solutions UK - Manchester',
    description: 'Specialists in damp proofing and building restoration. Surveying and inspections available.',
    rating: 5.0,
    reviews: 41,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-j-n-home-management-damp-proofing-specialist',
    name: 'J.N Home Management Damp proofing specialist',
    description: 'Specialists in damp-proofing and water damage restoration.',
    rating: 5.0,
    reviews: 20,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-sbc-damp-proofing',
    name: 'SBC Damp Proofing',
    description: 'Specialists in damp proofing and building restoration. Comprehensive construction services.',
    rating: 4.5,
    reviews: 70,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-complete-plastering-and-damp-proofing-solutions-ltd',
    name: 'Complete Plastering and Damp Proofing Solutions Ltd',
    description: 'Construction and damp-proofing specialists.',
    rating: 3.7,
    reviews: 3,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-w-evans-damp-proofing',
    name: 'W. Evans Damp Proofing',
    description: 'Professional damp proofing and surveying services.',
    rating: 4.5,
    reviews: 8,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-m-a-dampcure',
    name: 'M.A Dampcure',
    description: 'Professional damp treatment and specialist services.',
    rating: 4.7,
    reviews: 50,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
  {
    id: 'manchester-timberwise-uk-ltd',
    name: 'Timberwise (UK) Ltd',
    description: 'Specialists in damp treatment and building restoration. Professional surveying services.',
    rating: 4.8,
    reviews: 12,
    verified: true,
    services: ['Damp Proofing'],
    priceRange: '££',
    location: 'Manchester',
  },
];

export const RECOMMENDATIONS = [
    {
        id: 'rec1',
        title: 'Wall Insulation',
        description: 'Install internal or external wall insulation to reduce heat loss.',
        impact: 'High',
        estimatedCost: '£5,000 - £8,000',
        annualSavings: '£450',
        co2Reduction: '1.2 tons',
        priority: 'High',
    },
    {
        id: 'rec2',
        title: 'Heat Pump Upgrade',
        description: 'Replace your gas boiler with an efficient air source heat pump.',
        impact: 'Very High',
        estimatedCost: '£10,000 - £14,000',
        annualSavings: '£800',
        co2Reduction: '2.5 tons',
        priority: 'Medium',
    },
    {
        id: 'rec3',
        title: 'Smart Thermostats',
        description: 'Install smart controls to better manage heating schedules.',
        impact: 'Low',
        estimatedCost: '£200 - £300',
        annualSavings: '£120',
        co2Reduction: '0.3 tons',
        priority: 'Low',
    },
];

export const GRANTS = [
    {
        id: 'g1',
        name: 'Boiler Upgrade Scheme',
        amount: '£7,500',
        description: 'Grant to replace fossil fuel heating systems with heat pumps or biomass boilers.',
        eligibility: 'Homeowners in England and Wales',
    },
    {
        id: 'g2',
        name: 'ECO4 Scheme',
        amount: 'Full Cost',
        description: 'Support for low-income households to improve energy efficiency.',
        eligibility: 'Low income or benefits recipients',
    },
];

