export const PROVIDERS = [
    {
        id: '1',
        name: 'EcoWarm Solutions',
        description: 'Specialists in high-efficiency insulation and heat pumps.',
        rating: 4.8,
        reviews: 124,
        verified: true,
        services: ['Insulation', 'Heat Pumps'],
        priceRange: '££',
        location: 'London',
    },
    {
        id: '2',
        name: 'SolarTech Pros',
        description: 'Leading installers of solar panels and battery storage systems.',
        rating: 4.9,
        reviews: 89,
        verified: true,
        services: ['Solar', 'Battery Storage'],
        priceRange: '£££',
        location: 'Manchester',
    },
    {
        id: '3',
        name: 'GreenGlaze Windows',
        description: 'Double and triple glazing experts for period properties.',
        rating: 4.7,
        reviews: 56,
        verified: true,
        services: ['Windows', 'Doors'],
        priceRange: '££',
        location: 'Bristol',
    },
    {
        id: '4',
        name: 'PureAir Ventilation',
        description: 'Modern ventilation systems to prevent damp and mold.',
        rating: 4.6,
        reviews: 42,
        verified: false,
        services: ['Ventilation', 'Damp Proofing'],
        priceRange: '£',
        location: 'London',
    },
];

export const RECOMMENDATIONS = [
    {
        id: 'rec1',
        title: 'Wall Insulation',
        description: 'Install internal or external wall insulation to reduce heat loss.',
        impact: 'High',
        estimatedCost: '£5,000 - £8,000',
        annualSavings: '£450',
        co2Reduction: '1.2 tons',
        priority: 'High',
    },
    {
        id: 'rec2',
        title: 'Heat Pump Upgrade',
        description: 'Replace your gas boiler with an efficient air source heat pump.',
        impact: 'Very High',
        estimatedCost: '£10,000 - £14,000',
        annualSavings: '£800',
        co2Reduction: '2.5 tons',
        priority: 'Medium',
    },
    {
        id: 'rec3',
        title: 'Smart Thermostats',
        description: 'Install smart controls to better manage heating schedules.',
        impact: 'Low',
        estimatedCost: '£200 - £300',
        annualSavings: '£120',
        co2Reduction: '0.3 tons',
        priority: 'Low',
    },
];

export const GRANTS = [
    {
        id: 'g1',
        name: 'Boiler Upgrade Scheme',
        amount: '£7,500',
        description: 'Grant to replace fossil fuel heating systems with heat pumps or biomass boilers.',
        eligibility: 'Homeowners in England and Wales',
    },
    {
        id: 'g2',
        name: 'ECO4 Scheme',
        amount: 'Full Cost',
        description: 'Support for low-income households to improve energy efficiency.',
        eligibility: 'Low income or benefits recipients',
    },
];
